### ISSUE TITLE
Request: update to more modern codebase (restartless, SDK)

### ISSUE THREAD

**Issue by TheRealMarnes** [benbasson/imagetoolbar#12]
This is a nice addon, but restartful addons are a thing of the past. Using the SDK and otherwise generally following Mozilla's plans for addons makes them easier to maintain for devs and gives users a better experience. I'm personally also sceptical about the performance and stability and such of addons that use their own code for everything instead of using the SDK and whatnot.

**Comment by TheRealMarnes** [comment]
Perhaps useful info, among other pages: https://developer.mozilla.org/en-US/Add-ons/How_to_convert_an_overlay_extension_to_restartless

**Comment by benbasson** [comment]
Unless the new SDK has progressed significantly since last time I looked, I'd be surprised if this add-on can be ported to it. 

The main issues are: 
1) binding the functionality onto images - I'm using XBL because it works consistently, trying to add event listeners to every image on every page load is difficult and more CPU intensive. I don't think XBL is as easily available in the new world.
2) the save/download functionality in the SDK used to be complete rubbish, maybe it's better now.

To be frank, I don't think having to restart a browser is the end of the world and unless non-SDK add-ons are going to be desupported completely, I suspect I will not port Image Toolbar.

With regards to your concern about performance, this add-on has been available for a decade and nobody has ever reported problems.

**Comment by TheRealMarnes** [comment]
Fair enough, no arguments there.

As for 1 and 2: the SDK lets you inject scripts into pages and provides a communication channel between the main code and each injected script. I've already made an addon that succesfully overlays a button over any image on mouse hover (with graphics embedded in the addon), updates the button's position on scroll (using jquery to save some finicky work, admittedly), downloads the image to a local file upon clicking the button (the button can use the comms channel to relay the image's URL to the main code, letting you download, print, log, whatever you like) and does it all with just 2 eventlisteners per page (mouseover and mouseout event on the document body, with event.target being filtered). The only finnicky part to downloading with the SDK (but I think it counts for anything, so not really a valid point) is that you need to provide a filename yourself, which one of my other addons accomplishes by doing a HEAD request and parsing anything useful out of the URL. I'd be happy to share my code with you once I release it (soon), if you'd be interested. I put the code of all my addons on github anyway.

**Comment by benbasson** [comment]
FYI - I'm probably going to be forced to do this soon because of Mozilla's new "break all add-ons for minor performance gains" policy.

**Comment by benbasson** [comment]
Update to the last. This add-on will likely have to be completely rewritten as a WebExtension add-on by the end of 2017, or it will cease to exist. Frankly, it makes the chances of me porting Image Toolbar to the SDK almost completely non-existent. 

Of all the add-ons I've written, this one is probably the one I'm *most* confident about rewriting because it doesn't do anything involving the browser UI, apart from having settings, which I assume will still be possible in some form in the new world.

You can track this in issue #24.
